# Generated by Django 4.0.2 on 2022-02-06 09:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='from_number',
            new_name='external',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='to_number',
        ),
        migrations.AddField(
            model_name='conversation',
            name='internal',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1, max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='outward',
            field=models.BooleanField(default=True),
        ),
    ]
